version: '3.6'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"

volumes:
  storage: