version: '3.6'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app4:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app5:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  # traefik:
  #   image: traefik:2.10.7
  #   env_file:
  #     - .env
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - "./traefik/traefik.toml:/etc/traefik/traefik.toml"

  nginx:
    image: nginx:latest
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

volumes:
  storage: