version: '3.6'

services:
  common:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage
    image: musuyaba/artificer-qr-code-gen

  app1:
    extends:
      service: common

  app2:
    extends:
      service: common

  app3:
    extends:
      service: common

  app4:
    extends:
      service: common

  app5:
    extends:
      service: common

  aio:
    container_name: artificer-aio-run
    build:
      context: .
      dockerfile: aio.Dockerfile
      args:
        - HOST_PROXY=${HOST_PROXY}
    volumes:
      - qr-storage:/app/storage
    ports:
      - "80:80"
    environment:
      - HOST_PROXY=artificer.localhost.local
    image: musuyaba/artificer-qr-code-gen-aio

  # traefik:
  #   image: traefik:2.10.7
  #   env_file:
  #     - .env
  #   ports:
  #     - "80:80"
  #     - "8080:8080"
  #   volumes:
  #     - "./traefik/traefik.toml:/etc/traefik/traefik.toml"

  nginx:
    image: nginx:latest
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

volumes:
  storage:
  qr-storage: