version: '3.6'

services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  app3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - storage:/app/storage

  nginx:
    image: nginx:latest
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"

volumes:
  storage: