name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Date and Time Variables
        id: datetime
        run: echo "::set-output name=formatted_date::$(date +'%Y%m%d%H%M')"

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker compose build common
          docker tag common:latest ${{ secrets.DOCKER_USERNAME }}/common:latest
          docker tag common:latest ${{ secrets.DOCKER_USERNAME }}/common:${{ steps.datetime.outputs.formatted_date }}
          docker push ${{ secrets.DOCKER_USERNAME }}/common:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/common:${{ steps.datetime.outputs.formatted_date }}
        env:
          DOCKER_BUILDKIT: 1
