name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Before Run Copy .env
        run: cp .env.example .env

      - name: Extract Version from .env
        id: extract_version_env
        run: |
          export VERSION=$(grep 'APP_VERSION=' .env | cut -d'=' -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

  determine_version:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set Git user information
        run: |
          git config user.email "musuyaba@gmail.com"
          git config user.name "Musuyaba Runner"

      - name: Determine the next version
        id: version
        run: |
          LAST_TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo "v1.0")
          MAJOR_VERSION="$VERSION"
          MINOR_VERSION=$(awk -F'.' '{print $2}' <<< "$LAST_TAG")
          NEXT_VERSION="$MAJOR_VERSION.$((MINOR_VERSION + 1))-$(date +'%Y%m%d%H%M')"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV

  release:
    runs-on: ubuntu-latest
    needs: [setup, determine_version]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Create Git tag
        if: success()
        run: git tag -a $NEXT_VERSION -m "Release $NEXT_VERSION"

      - name: Push Git tag
        if: success()
        run: git push origin $NEXT_VERSION

      - name: Generate Changelog
        if: success()
        run: |
          git log --pretty=format:"%s" $(git describe --tags --abbrev=0)..HEAD > changelog.txt
          echo "Changelog:"
          cat changelog.txt

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: [setup, release]

    steps:
      - name: Build and Push Docker Image
        run: |
          docker compose build aio
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{vars.DOCKER_AIO_REPO}}:latest ${{ secrets.DOCKER_USERNAME }}/${{vars.DOCKER_AIO_REPO}}:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{vars.DOCKER_AIO_REPO}}:latest ${{ secrets.DOCKER_USERNAME }}/${{vars.DOCKER_AIO_REPO}}:$NEXT_VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/${{vars.DOCKER_AIO_REPO}}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{vars.DOCKER_AIO_REPO}}:$NEXT_VERSION
        env:
          DOCKER_BUILDKIT: 1
